### ISSUE TITLE
Hi friend. Can you make an implementation for the protocol Goodweather?

### ISSUE THREAD

**Issue by ryoko-sky** [mistic100/ESPHome-IRremoteESP8266#1]

**Comment by mistic100** [comment]
Please try this:

```yaml
external_components:
  - source:
      type: git
      url: https://github.com/mistic100/ESPHome-IRremoteESP8266
      ref: goodweather
    components: [ goodweather ]

remote_transmitter:
  pin: GPIOXX
  carrier_duty_percent: 50%

climate:
  - platform: goodweather
    name: 'Living Room AC'
```

This platform has a specific implementation if the IR message, so I hope my implementation is correct
https://github.com/crankyoldgit/IRremoteESP8266/blob/master/src/ir_Goodweather.cpp#L32

Of course I will not be able to assist you if it does not work as it, if you have to make some edits, please report here so I can merge a working implementation.
