### ISSUE TITLE
ir_Fujitsu.h dependency error

### ISSUE THREAD

**Issue by FrancisBeland27** [mistic100/ESPHome-IRremoteESP8266#2]
I'm trying to build my ESPhome using the custom component but when I compile, I got the following error.

`src/esphome/components/fujitsu/fujitsu.h:7:10: fatal error: ir_Fujitsu.h: No such file or directory

********************************************************************
* Looking for ir_Fujitsu.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:ir_Fujitsu.h"
* Web  > https://registry.platformio.org/search?q=header:ir_Fujitsu.h
*
********************************************************************

    7 | #include "ir_Fujitsu.h"
      |          ^~~~~~~~~~~~~~
compilation terminated.
*** [.pioenvs/esphome-web-e6f0dc/src/esphome/components/fujitsu/fujitsu.cpp.o] Error 1`

**Comment by mistic100** [comment]
Could you share your config and the compile logs ? I am using the latest version of ESPHome on Home Assistant, the logs show that the dependency is installed (last one)

```
Dependency Graph
|-- AsyncTCP-esphome @ 2.1.4
|-- WiFi @ 2.0.0
|-- FS @ 2.0.0
|-- Update @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 3.3.0
|-- DNSServer @ 2.0.0
|-- ESPmDNS @ 2.0.0
|-- noise-c @ 0.1.6
|-- Wire @ 2.0.0
|-- ArduinoJson @ 6.18.5
|-- IRremoteESP8266 @ 2.8.6
```

**Comment by FrancisBeland27** [comment]
Here is my config:

```
esphome:
  name: esphome-web-e6f0dc
  friendly_name: Office IR Blaster  
  name_add_mac_suffix: false
  

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

external_components:
  - source: 
      type: git
      url: https://github.com/mistic100/ESPHome-IRremoteESP8266      
    components: [ fujitsu ]


logger:
  level: DEBUG 

api:

ota:
- platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password


remote_receiver:
  pin:
    number: GPIO4
    inverted: True
    mode: INPUT_PULLUP               
  dump: all

remote_transmitter:
  pin: GPIO5
  carrier_duty_percent: 50%
  id: ir_tx

climate:
  - platform: fujitsu  
    name: "Climatiseur Fujitsu"
    model: ARJW2
    supports_heat: False
    transmitter_id: ir_tx

```
Here is my compile log:

```
INFO ESPHome 2025.4.2
INFO Reading configuration /config/esphome/esphome-web-e6f0dc.yaml...
INFO Generating C++ source...
INFO Updating https://github.com/espressif/esp-protocols.git@mdns-v1.8.2
INFO Compiling app...
Processing esphome-web-e6f0dc (board: esp32-s3-devkitc-1; framework: espidf; platform: https://github.com/pioarduino/platform-espressif32.git#51.03.07)
--------------------------------------------------------------------------------
HARDWARE: ESP32S3 240MHz, 320KB RAM, 8MB Flash
 - framework-espidf @ 3.50105.0 (5.1.5) 
 - tool-cmake @ 3.21.3 
 - tool-esptoolpy @ 4.8.1 
 - tool-mklittlefs @ 3.2.0 
 - tool-ninja @ 1.10.2 
 - tool-riscv32-esp-elf-gdb @ 12.1.0+20221002 
 - tool-xtensa-esp-elf-gdb @ 12.1.0+20221002 
 - toolchain-esp32ulp @ 2.35.0-20220830 
 - toolchain-riscv32-esp @ 12.2.0+20230208 
 - toolchain-xtensa-esp32s3 @ 12.2.0+20230208
Reading CMake configuration...
No dependencies
Compiling .pioenvs/esphome-web-e6f0dc/src/esphome/components/fujitsu/fujitsu.cpp.o
Compiling .pioenvs/esphome-web-e6f0dc/src/esphome/components/mdns/mdns_component.cpp.o
Compiling .pioenvs/esphome-web-e6f0dc/src/esphome/components/mdns/mdns_esp32.cpp.o
Compiling .pioenvs/esphome-web-e6f0dc/src/esphome/components/mdns/mdns_esp8266.cpp.o
Compiling .pioenvs/esphome-web-e6f0dc/src/esphome/components/mdns/mdns_host.cpp.o
Compiling .pioenvs/esphome-web-e6f0dc/src/esphome/components/mdns/mdns_libretiny.cpp.o
Compiling .pioenvs/esphome-web-e6f0dc/src/esphome/components/mdns/mdns_rp2040.cpp.o
Compiling .pioenvs/esphome-web-e6f0dc/src/esphome/components/network/util.cpp.o
In file included from src/esphome/components/adc/adc_sensor.h:9,
                 from src/esphome.h:3,
                 from src/esphome/components/fujitsu/fujitsu.cpp:5:
/data/cache/platformio/packages/framework-espidf/components/esp_adc/deprecated/include/esp_adc_cal.h:17:2: warning: #warning "legacy adc calibration driver is deprecated, please migrate to use esp_adc/adc_cali.h and esp_adc/adc_cali_scheme.h" [-Wcpp]
   17 | #warning "legacy adc calibration driver is deprecated, please migrate to use esp_adc/adc_cali.h and esp_adc/adc_cali_scheme.h"
      |  ^~~~~~~
In file included from src/esphome/components/adc/adc_sensor.h:10:
/data/cache/platformio/packages/framework-espidf/components/driver/deprecated/driver/adc.h:19:2: warning: #warning "legacy adc driver is deprecated, please migrate to use esp_adc/adc_oneshot.h and esp_adc/adc_continuous.h for oneshot mode and continuous mode drivers respectively" [-Wcpp]
   19 | #warning "legacy adc driver is deprecated, please migrate to use esp_adc/adc_oneshot.h and esp_adc/adc_continuous.h for oneshot mode and continuous mode drivers respectively"
      |  ^~~~~~~
In file included from src/esphome.h:29:
src/esphome/components/fujitsu/fujitsu.h:7:10: fatal error: ir_Fujitsu.h: No such file or directory

********************************************************************
* Looking for ir_Fujitsu.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:ir_Fujitsu.h"
* Web  > https://registry.platformio.org/search?q=header:ir_Fujitsu.h
*
********************************************************************

    7 | #include "ir_Fujitsu.h"
      |          ^~~~~~~~~~~~~~
compilation terminated.
*** [.pioenvs/esphome-web-e6f0dc/src/esphome/components/fujitsu/fujitsu.cpp.o] Error 1
========================= [FAILED] Took 20.20 seconds =========================

```

**Comment by mistic100** [comment]
Try using Arduino instead of ESP IDF

**Comment by FrancisBeland27** [comment]
Choosing arduino installed the IRremoteESP8266 thank you. However it did not load the climate entity on it. It might be related to the following warning I had when compiling:


WARNING Using `climate_ir.CLIMATE_IR_WITH_RECEIVER_SCHEMA` is deprecated and will be removed in ESPHome 2025.11.0. Please use `climate_ir.climate_ir_with_receiver_schema(...)` instead. If you are seeing this, report an issue to the external_component author and ask them to update it. https://developers.esphome.io/blog/2025/05/14/_schema-deprecations/. Component using this schema: fujitsu

**Comment by mistic100** [comment]
I don't think so, it is a deprecation notice, not and error.

**Comment by FrancisBeland27** [comment]
I had this problem since updating to the newest version of ESPHome on my device. I tried to use the normal fujitsu_general from the official ESPHome and I do have the climate entity (it's not working). Can you change what is listed in the deprecation so we can test if it is the problem?

**Comment by FrancisBeland27** [comment]
For this issue, however, using arduino solved it so I'll close it.

**Comment by mistic100** [comment]
I don't think the problem is in this deprecation, but other changes in the Python API

I rewrote the climate.py file by copying https://github.com/esphome/esphome/blob/dev/esphome/components/gree/climate.py

Try with this (I won't try it myself)

```yaml
external_components:
  - source:
      type: git
      url: https://github.com/mistic100/ESPHome-IRremoteESP8266
      ref: compat
    components: [ fujitsu ]
```
