### ISSUE TITLE
Panasonic AC

### ISSUE THREAD

**Issue by kenwang92** [mistic100/ESPHome-IRremoteESP8266#4]
Hello,

I'm currently using [this project](https://github.com/Mixiaoxiao/ESP8266-IR-HOMEKIT), and I was able to successfully control my Panasonic AC by flashing it to an ESP8266.

I noticed that the project uses the IRremoteESP8266 library, and I'd like to migrate this functionality over to ESPHome.

Would you be able to help me with this migration, or could you advise me on how I might do it myself?

**Comment by mistic100** [comment]
If you want to submit a PR to support Panasonic AC, take a look at how Fujitsu is implemented https://github.com/mistic100/ESPHome-IRremoteESP8266/tree/main/components/fujitsu

it is globally a simple mapping between ESPHome state and IRremoteESP8266 calls. The only tricky part is the `transmit_state` method which must be reimplemented by using IRremoteESP8266 for reference but with ESPHome API.

**Comment by mistic100** [comment]
Started something on this branch https://github.com/mistic100/ESPHome-IRremoteESP8266/tree/panasonic

I don't know if it compiles

**Comment by kenwang92** [comment]
Sure, thanks for the information. I'll find some time to give it a try.

**Comment by mistic100** [comment]
FYI I just added a way to change the orientation of the exhaust ("Set" button on my remote) for the Fujitsu platform.

Don't hesitate to tell me if you want such stateless calls available for Panasonic (ideally share a picture of youre remote so I known what corresponds to what)

By stateless I mean other functions than the one supported my the climate integration (namely mode, temp, fan speed, and swing)

**Comment by mistic100** [comment]
I have fixed the compilation, please try this

```yaml
external_components:
  - source:
      type: git
      url: https://github.com/mistic100/ESPHome-IRremoteESP8266
      ref: panasonic
    components: [ panasonic, ir_remote_base ]

remote_transmitter:
  pin: GPIOXX
  carrier_duty_percent: 50%

climate:
  - platform: panasonic
    model: XXX
    name: 'Living Room AC'
```
